### ISSUE TITLE
Varnish: 106 Message from VCC-compiler: Inline-C not allowed

### ISSUE THREAD

**Issue by 2des** [nexcess/magento-turpentine#1080] opened 2016-01-25 16:34 UTC
I am using CentOS 7 with Varnish 4, Magento 1.9.2.3

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Inline-C not allowed ('input' Line 2 Pos 1) C{ ## Running VCC-compiler failed, exited with 2 VCL compilation failed

I have made those changes in: https://github.com/nexcess/magento-turpentine/issues/948#issuecomment-141805671

when i add the -p vcc_allow_inline_c=on line. restart ok.
when applying the Varnish Config, blank page, and the site not load.

Varnish restart, and its working again until Apply Varnish Config.

Thank you, for helping, i have tried everything.
Best regards
2D

**Comment by miguelbalparda** [comment] 2016-01-25 16:36
Have you seen anything unusual in your server logs?

**Comment by 2des** [comment] 2016-01-25 17:56
Hello,

/var/log/varnish/varnish.log was huge, it can`t be opened, i save (file size changed a lot) that every page load are logged. I deleted the log file, and restarted the server. now the log file isn't recreated. i created the file, but its empty :)

**Comment by miguelbalparda** [comment] 2016-01-26 12:17
How about your apache and php logs?

**Comment by ADDISON74** [comment] 2016-01-31 13:33
What Turpentine version are you using? Is it the devel branch? In case yes, the latest devel branch as an issue. Turpentine creates a wrong Varnish configuration file, there is a syntax issue. Even your Varnish service starts great and working without Turpentine file, using this devel version creates you trouble. I suggest using a devel version from December 2015. Master branch has issues too. Check the report for devel branch here #1085.

**Comment by 2des** [comment] 2016-01-31 14:36
Hello ADDISON74,
I have downloaded the latest version: 17 day old modified.
please send me a good working version link, or email me on office [at] 2design [dot] ro
Thank you.
Best regards.

**Comment by miguelbalparda** [comment] 2016-01-31 14:40
We haven't confirmed any issues with devel or master yet. I strongly suggest you to keep using the latest master version until further notice.

**Comment by ADDISON74** [comment] 2016-01-31 14:53
You haven't confirmed any issues because people are not actively involved in helping you with this project. I am one who really respect your work and helps you going further. With all due respect the latest master branch has issues as you already know from this issue #1086.

**Comment by ADDISON74** [comment] 2016-02-01 17:43
@2des It seems there are issues in CentOS 7 + Varnish 4.0.3. Even you get it working it won't give you any satisfaction. You will spend more and more time to debug like I did this weekend for nothing. I suspect Varnish 4.0 from EPEL repo is build without some options or has bugs. For example Turpentine cache option [Varnish ESI Blocks] is not working, if is enabled your page content and side blocks are disappearing. I suggest wait for Turpentine being ready for Varnish 4.1 or switch to other Linux distro, like Debian 7. Everything is working as expected in Debian.

**Comment by ADDISON74** [comment] 2016-02-02 10:33
@2des: You can close this issue.

**Closed** 2016-04-01 18:28 UTC
Labels: question
