### ISSUE TITLE
Magento 1.9.1 - [Recently Compared Products] side block is being cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#803] opened 2015-06-14 09:43 UTC
Testing version installed from scratch, no other extensions. Magento CE 1.9.1 out of box, Varnish 3, Turpentine.

[Recently Compared Products] side block is being cached! I tried to set up ESI policies for it but it is not working at all.

Please take a look to see what is going wrong. If you need a testing version just let me know. Thank you.

**Comment by aricwatson** [comment] 2015-06-24 13:39
I believe this is due to a misconfiguration, I could not replicate using fresh install of 1.9.1 and Turpentine. Closing until further information provided.

**Comment by aricwatson** [comment] 2015-06-24 14:14
Apologies, I was looking at the *compare products* box (need more coffee!) I was able to replicate this, will work on a fix.

**Comment by ADDISON74** [comment] 2015-06-24 21:00
This is great. I will help you asap with more information if you need.

**Comment by aricwatson** [comment] 2015-06-25 02:44
Can you give me steps to reproduce this?

**Comment by ADDISON74** [comment] 2015-06-25 09:09
You have to clear your cache and have also a plan for visiting categories and adding products to compare. The just add and compare different products, then clear one item or all. Go visiting the same categories from where you started this test and you can reproduce it.

**Comment by ADDISON74** [comment] 2015-06-28 20:59
I will come back to you will the right steps in order to reproduce this issue.  I managed to get the issue even there is an ESI set up apparently correct for this block.

**Comment by aricwatson** [comment] 2015-07-08 15:02
@ADDISON74 were you able to find specific steps to replicate the issue?

**Comment by ADDISON74** [comment] 2015-07-08 21:00
!! PLEASE PRINT THIS BEFORE DOING THE TEST !!

Clear all caches, frontend cookie, to start from scratch. I restarted Varnish and Apache services too. This is for Magento 1.9.1 with sample data and RWD theme, the default one.

1) Go to VIP category which has 6 items. Add 4 items to comparison. Page refreshes every time and you will have a correct "Compare Products" side block with 4 items inside.

2) Click on [Compare] button in "Compare Products" side block. A new window is coming in frontend (Compare Products). Delete two items then close the window. When you delete a product inside Compare window your "Compare Products" side block is updating according to your options.

3) Go to Men -> Pants & Denim category. You will see now "Recently Compared Items" above "Compare Products". Both side blocks have 2 items inside. Do again a comparison by clicking on [Compare] button, close the Compare Products window and click on [Clear All] button in side block "Compare Products". SURPRISE, you are now in VIP category not inside Men -> Pants & Denim!

4) Go to Women => Pants & Denim category. "Recently Compared Products" side block has two items inside, this is not correct at all. The items are from first comparison. Normal behavior should present 4 products. Please note there is an ESI tags around "Recently Compared Products", 

5) Click [Add to Compare] button for any product inside this category. SURPRISE again, now "Recently Compare Products" side block has 4 products inside, which is correct. 

There are two issues identified by me: 

1) When you click [Clear All] button you are redirect to previous category.
2) "Recently Compared Products" side block is not updating, but when you [Add to Compare] even one product it will update.

Thank you.

**Comment by ADDISON74** [comment] 2015-07-08 21:04
OT - please revise my two questions from this closed issue: https://github.com/nexcess/magento-turpentine/issues/801

Thank you.

**Comment by aricwatson** [comment] 2015-07-08 21:08
Thank you @ADDISON74 I will test with these steps tomorrow.

**Comment by aricwatson** [comment] 2015-07-09 19:33
I've verified these two bugs - abbreviated steps to replicate below:

**clear all compared bug**
To reproduce:
1. start a new session and go to a category page
2. click "add to compare" to add a product to the compare box
3. navigate to a *different* category
4. click "clear all" in the side block

You will end up on the category where you added the product from  and *not* the category where you clicked "clear all"

**recently compared bug**
To reproduce:
1. start a new session and go to a category page
2. click "add to compare" to add a product to the compare box
3. click "clear all" in the side block

You should see the product listed in a 'recently compared products' box on the right side. It isn't there, but if you then click 'add to compare' for another item - the recently compared box will appear.

I suspect the blocks need some more flush events defined, I'll see what I can find.

**Comment by ADDISON74** [comment] 2015-07-09 21:13
It is a pleasure working with you. Please note this issue is active in 1.8 CE branch too. I guess if you find a solution it will apply for those who are using this version.

By the way I switched to Magento 1.9.2 this evening. So far, so good.

**Comment by ADDISON74** [comment] 2015-07-31 12:09
any news related to this issue? for the moment I disabled comparison but I have to enable once you find a solution. 

when you add to compare a product that will be the page you will be redirected after clicking on Clear All button. I added a product for comparison directly in product page. I visited other sections. When I cleared all, the page reloads with product page content. 

this is a very annoying issue and it is a long time bug in Turpentine.

**Comment by ADDISON74** [comment] 2015-07-31 12:37
By the way I used varnishlog like a novice and after using [Clear All] button there are some records saying:

ExpBan c 1885352490 was banned

I never saw this banning for other pages before.

**Comment by ADDISON74** [comment] 2015-07-31 13:41
If you add products from 3 - 4 categories then Clear All, you will be transfer to the last category where you added your last product for comparison.

**Comment by aricwatson** [comment] 2015-07-31 14:15
Actually, spent a good chunk of time on this over the last few days. Currently it seems to be related to this issue: http://stackoverflow.com/questions/17799627/magento-how-is-the-recently-compared-template-removed-from-the-layout-when-it

Basically, the block has it's toHtml() which outputs nothing if there are no recently compared products. Turpentine uses toHtml to inject the ESI for the block. But nothing is getting injected when there are recently compared items.

We're looking into the best fix for this.

**Comment by ADDISON74** [comment] 2015-08-06 21:16
I installed Debian Jessie. After managing the bug related to systemd/varnish/listen port 80, I put Turpentine dev-4 at work with Varnish 4. So far, so good. This issue related to Recently Compared Products is it active. Also the one related to Recently Added to Cart too. Surprising predictive search it is working by default.

By the way, Varnish 4 exceeds the expectations with your Turpentine 4. In Debian Wheeze, Varnish 3, Turpentine 3, I got for the ab test with  -n 1000 -c 100 around 1300 requests/second, the best result. Now in Debian Jessie, with Apache 2.4, PHP 5.6 with OpCache I get 3200 requests/second. Almost 3 times faster!

Please try to fix the bugs related to what I report to default Magento. 

Question: Is it ready for production Varnish 4 & Turpentine 4 (you should call it like that avoiding issues with current version)?

**Comment by aricwatson** [comment] 2015-08-07 14:20
Sounds promising. I'm not surprised that recently compared and recently added issues are still there, as they seem to be related to how core magento handles those blocks, so we're still looking for a good workaround. Once those are (hopefully) fixed, it should fix them for Varnish 3 and 4.

The Varnish 4 branch is pretty stable, although we're still testing it. So I'm not going to promise no problems :)

**Comment by aricwatson** [comment] 2015-08-10 17:36
Hi @ADDISON74 - I just created a pull request (https://github.com/nexcess/magento-turpentine/pull/882) with fixes for this problem. Please test the PR and see if it fixes it for you. It also should fix a similar issue with the 'recently viewed products' block.

**Comment by ADDISON74** [comment] 2015-08-11 08:40
I downloaded all 4 files and replaced those I have on my test server. I cleared the whole cache, restarted Varnish and Apache, cleared all cookies. After a few minutes of testing it seems the issues related to Recently Viewed Products and Recently Compared Products are solved. Both side blocks are updating according the last visited products and compared. I will keep testing on this in the next days.

I guess the same solving should be applied to Recently Added Products to Cart side block. This is an open issue too.

There is one annoying issue you should investigate: [Clear All] button in side block "Compare Products". This button once it is pushed will clear the comparison list, but instead of keeping you on the same page you will be redirected to the last page you added a product. E.g. I go to Category A, add 2 products for comparison then go to Category B adding 2 more products for comparison, then go to Category C. Now I have 4 products for comparison. If I click [Clear All] button the action clears correctly the side block, but will redirect me to the Category B (the last page I added products for comparison, before clearing).

**Comment by ADDISON74** [comment] 2015-08-11 08:56
One more thing. I would like to ask you how this "Recently Side Compare" block works. If I add items for comparison are they considered compared? Or they are considered compared after clicking [Compare] button in side block?

Why I am asking this? Because I add products to comparison, but I clear the list. All products appear as compared inside "Recently Compared Products" side block. If I am remember without Turpentine/Varnish combination when I was clearing the list, those products were not considered compared without doing a real compare on them. But I could mistake with this statement.

**Comment by aricwatson** [comment] 2015-08-11 18:14
> One more thing. I would like to ask you how this "Recently Side Compare" block works. If I add items for comparison are they considered compared? Or they are considered compared after clicking [Compare] button in side block?

Yeah, the name of the block is a little misleading. It actually lists products that were in the compare box, but are no longer. So, you can get an item to show up in the 'recently compared' block by clicking it's 'add to compare' link, then on one of the screens where the block is show, click to remove it. Then, it'll show up  in the 'recently compared' block.

> This button once it is pushed it will clear the comparison list, but instead of keeping you on the same page you will be redirected to the last page you added a product.

Yes, there does seem to be some issues w/how Varnish/Turp handle these sorts of scenarios - we're sitll investigating/testing.

**Comment by aricwatson** [comment] 2015-08-12 16:40
OK, we've merged the fix for the recently compared and recently viewed blocks. I haven't looked yet, but I suspect that the recently added block issue you mentioned is related, so once I get a chance to investigate it'll hopefully be a quick fix!

**Closed by aricwatson** 2015-08-12 16:40 UTC
Labels: bug

**Comment by ADDISON74** [comment] 2015-08-19 09:00
[Clear All] button seems to be the same issue like in Community Poll issue. When I voted I was kept on the same page. Clear All moves me to the last product I added for comparison. It could be AJAX issues. Could you please check?
