### ISSUE TITLE
New Relic performance help

### ISSUE THREAD

**Issue by gregdev** [nexcess/magento-turpentine#772] opened 2015-04-14 08:29 UTC
Hey all, I'm using Turpentine 0.6.0 with Magento CE 1.7.0.2 and Varnish 3.0.6. In New Relic, by far the most time consuming transaction is /turpentine/esi/getBlock; the breakdown for this shows the WebTransaction component of this taking up 90% of the transaction time. I'm just wondering if this is expected behaviour, or if this points to a problem with my setup. The transaction uses a fair chunk of time, so anything I could do to reduce this would be beneficial!

Here's a screenshot from New Relic showing the transaction overview:

![new-relic](https://cloud.githubusercontent.com/assets/1578099/7133201/eb5dca8a-e2cf-11e4-8c4a-9e60fa10dce8.png)

Any advice would be very much appreciated!
Cheers

**Comment by evensis** [comment] 2015-04-14 09:40
That's unusually high but its totally dependent on any resource intensive custom blocks you have, if you have a custom ESI block that is doing an awful lot and is resource intensive expect a high response time. However, we're seeing issues with Turpentine creating sessions spuriously and tanking up the Redis session storage. We're seeing response times ranging from 300ms (which is fine), to around the same level you're seeing when the session storage gets chockablock with useless sessions (and has duplicated json data as well), typically from bots.

I would set up a key transaction in newrelic, bring the apdex response right down so you get some slow query logs, that way you will be able to nail down exactly what is causing the slow responses. Wouldn't be surprised to see session reads being the culprit.

**Comment by gregdev** [comment] 2015-04-14 23:25
Thanks mate, I've added this as a key transaction and will see how I go.

If it turns out it is to do with session reads, what's the best method to resolve this? Is it safe to clear out the Redis session storage in some way without interrupting customers / clearing carts / etc?

Cheers

**Comment by evensis** [comment] 2015-04-15 10:03
Unfortunately not, when our website is absolutely crawling, we have no alternative but to do the full flush.

Redis-cli on command line followed by flushall.

I haven't had time to investigate the cause, if you look at some of the keys in Redis you'll notice a huge lump of sessions being created by individual ESI calls. Also the data in the sessions are erroneous, examples being user agents duplicated a few times (i've seen some keys with this data duplicated 6 times).

The interesting thing about this, is I have applied the fix for getFormKey() #516 , which should prevent ESI calls from creating sessions. Though this clearly isn't the case as ESI calls are definitely creating sessions, perhaps this is being called from within the Turpentine code base.

I also dropped bot session lifetime (local.xml) from an hour down to 5 minutes, which has dropped the roughly 17,000 keys we had open at any one time down to around the 4000 mark (which is still full of a lot of ESI sessions).

It's highly unlikely we'll see any fix from @aheadley as it appears he hasn't looked at this project in more than 6 months, so will be down the community to resolve this one unfortunately!

We are moving to Enterprise, so will be dropped Turpentine in favour of Magento Enterprise's Full page cache backed up by Redis. So I haven't been given time to look into the problem!

**Comment by aricwatson** [comment] 2015-07-08 14:18
If you're still working on this problem, the current *devel* branch may solve the problem, by getting rid of the unnecessary session creation issue.

**Comment by aricwatson** [comment] 2015-07-10 13:34
@evensis is this issue also resolved by the GSF2 issue you mentioned in https://github.com/nexcess/magento-turpentine/issues/806?

**Comment by aricwatson** [comment] 2015-08-03 13:33
Closing for lack of feedback.

**Closed by aricwatson** 2015-08-03 13:33 UTC
