### ISSUE TITLE
Compare, Compared and remove info message - ALL CACHED!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#716] opened 2015-01-06 21:48 UTC
It is so easy to check what is cached or not. Just use Back/Forward buttons in your browser to get the magic. Well I found side blocks Product Compare and Product Compared are both cached. I checked if there are ESI rules for them and again like for Community Poll, there are rules set up. You can add products to comparison, go visiting other page add one more. Go back to initial added product, block Compare shows one product instead of two products.

After you comparef and removed products you will see Recently Compared Products block appearing. This is completely compromised too showing wrong number of products or compared products.

And finally one more thing "I like" is related to message box. After you remove a product from comparison you will get this message inside a green box: "The product XXXXXX has been removed from comparison list." Go visit another product and go back. Message is still there.

This extension is very useful but painful using as it is now. Really folks if you cannot deal with Magento stock why providing it? Why a release without basic checking? I was beta tester for a lot of shopping carts, some of them very popular. I dedicated my time to improve this extension. But when I see there is no response from the development team I regret a lot spending my time in digging it for issues.

**Comment by anderow** [comment] 2015-01-07 09:11
Interesting discovery, nice one. You have made a lot of input into this extension from my extensive reading I have done on this group. I can't find anything from the dev team either. I have an ongoing issue with this extension and Varnish 4 but cant get any assistance to sort it. I realise V4 is not supported but I think it should be seeing as turpentine allegedly supports Magento 1.9.1

**Comment by ADDISON74** [comment] 2015-01-07 09:35
Community Poll has an interesting issue I don't understand. It is astonishing nobody from Nexcess did not finding yet. It is related to all versions of Magento starting with 1.7.

Using comparison is compromised because side block Compare Products and Recently Compared Products are both cached. Also the message information when you remove a product from compare in side block is cached. 

I understand there are problems with Varnish 4, it is not supported yet. But let's find a way all together to give a good shape to this extension and release it working for Magento default. Then if someone wants more related to custom blocks or extensions to have a good tutorial to solve himself the issues.

Really guys, Magento needs Varnish. It is a slow shopping cart. Without Turpentine you will have a lazy store and not far from the other carts. Nexcess policy is wrong if only money count. Shining your company name means your products are mass distributed and becoming "must have" in all Magento shopping carts. I am here to help and I hope to find more and more interested to give a good shape to this extension.

**Comment by gewaechshaus** [comment] 2015-01-09 01:04
I noticed a related behaviour with an individual block and the turpentine_esi.xml. As long as i reference the block in turpentine_esi.xml, esi won't ever work. This doesn't happen on every block, but seems to appear to some as in my individual case, or to some native blocks like welcome. If i setup the my esi related stuff in the extensions layout.xml, esi is rendered like it should. I think the problem is related to the magento core and some of the rendering html methods.

**Comment by gewaechshaus** [comment] 2015-01-09 01:35
Recently viewed items block is also a candidate. Doesn't seem to work with the default turpentine_esi setup, will try the same workaround as with my individual block tomorow.

**Comment by gewaechshaus** [comment] 2015-01-09 10:51
I did some tests, maybe you can do some more testing.

Putting the following piece of code into turpentine_esi results in the block never seems to be holepunched:

      <reference name="right.reports.product.viewed">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <catalog_controller_product_view/>
                    </flush_events>
                </params>
            </action>
        </reference>

If i put the following piece into my local.xml, ESI is working as is should
  <reference name="right">
          <block type="reports/product_viewed" before="right.permanent.callout" name="right.reports.product.viewed" template="reports/product_viewed.phtml" >
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <method>esi</method>
                </params>
            </action>
          </block>
    </reference>

So this seems to be a problem related to some layout xml and structures...

**Comment by ADDISON74** [comment] 2015-01-09 21:02
Recently Viewed Products right side block is cached too. I will follow your advice. Maybe we can solve the mystery related to other side blocks like Recently Compared Products, Community Poll and info message after we remove a product from compare list (Compare side block).

**Comment by gewaechshaus** [comment] 2015-01-09 21:11
Yes... I hope so ;)

**Comment by ADDISON74** [comment] 2015-01-09 21:30
@gewaechshaus related to your solution for Recently Viewed Products side block. Delete your browser cache, cookies, magento sessions and cache. 

Visit your Home Page then visit one of you category:

- Open in new tab Product 1: Recently Viewed Products is not appearing
- Open in other tab Product 2: Recently Viewed Products shows Product 1 and Product 2
- Open in other tab Product 3: Recently Viewed Products shows Product 1, Product 2, Product 3

Now you have 4 tabs: Category, Product 1, Product 2, product 3. 

- Refresh Category page: Recently Viewed Products side block is not appearing (it is not good at all)
- Refresh Product 1 page: Recently Viewed Products side block is not appearing (it is not good at all)
- Refresh Product 2 page: Recently Viewed Products side block shows 3 products (it is normal)
- Refresh Product 3 page: Recently Viewed Products side block shows 3 products (it is normal)

Let's visit Category 2 page. Recently Viewed Products side block shows 3 products (it is normal). But if you visit a new product, this category will show you 3 products. 

You solution it is not working with categories and first product visited after a category. Just check and come back to me. Anyway you improved a lot in a good direction the code.

**Comment by ADDISON74** [comment] 2015-01-09 22:12
I installed a Magento 1.8 stock without Turpentine. I followed all my steps from above.

1) If you refresh category page it won't show Recently Viewed Products right side block.

2) But if you visit all those 3 product pages and refresh them, you will get Recently Viewed Products side block SHOWING THE OTHER 2 PRODUCTS but NOT THE ONE YOU REFRESHED!

Let's say we visited 4 products in 4 tabs. If we refresh all 4 pages we will get 3 products in Recently Viewed Products side block, the missing product link is the current page. 

Using Turpentine the show begins with wrong results: the very first product visited will not load Recently Viewed Product side block even we refresh many times the page. This is not good, something is still wrong there with its ESI cache rule.

**Comment by gewaechshaus** [comment] 2015-01-09 23:12
I have to recheck this, which isn't as easy cause we are in a productional environment... I will pm you the URL to do some tests. Maybe some of the turpentine methods are corrupted, this need a deep inspection.

**Comment by ADDISON74** [comment] 2015-01-10 22:17
First category you visit, won't show Recently Viewed Products, even you refresh the page. Then first product you visit after the category won't show Recently Viewed Products too. If you continue visiting products and refreshing pages everything goes normal.

This side block has an proved issue.

**Comment by gewaechshaus** [comment] 2015-01-11 15:40
After some quick logging, it seems that the block won't pass the check in most cases, turpentine seems to inject the block  only in a very few cases 

    TURPENTINE: Checking ESI block candidate: right.reports.product.viewed.turpentine

     TURPENTINE: Checking ESI block candidate: right.reports.product.viewed.turpentine
     TURPENTINE: Block check passed, injecting block: right.reports.product.viewed.turpentine

**Comment by ADDISON74** [comment] 2015-02-11 16:23
This is really bad. What a shame to have an unfinished extension for Magento ...

By the way, why Nexcess is not telling us this extension is not supported anymore? It will help all a lot such of message.

**Comment by aricwatson** [comment] 2015-07-08 16:05
Closing this issue in favor of your more recent issue https://github.com/nexcess/magento-turpentine/issues/803

**Closed by aricwatson** 2015-07-08 16:05 UTC
